-- RELATIONSHIPS IN SQL
-- 1. One-to-many relationships e.g an artist with different album or an authors with their books directors

-- 2. One-to-One Relationships: This implies unique pairings btw entities and are therefor less common.
        -- A commanly held premise of forensic science is that no two fingerprints are identical, and therefore a particular fimgerprint can only be generated by on person.

-- 3. Many-to-Many Relationships: An example of this is Lanagues and Countries i.e Many languages can be spoken in Many countries.k